name: Push docs

on:
  push:
    branches:
      - master

jobs:
  mkdocs-build-and-push:
    name: mkdocs and push to docs.donkeycar.com
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          python-version: 3.9
          auto-activate-base: true
          channels: defaults, conda-forge
      - run: |
          conda info
          conda list
          conda install mkdocs
          pip install mkdocs-redirects
          pip install mkdocs-material
          mkdocs gh-deploy --force -v
          echo Docs were made and pushed to docs.donkeycar.com